### ISSUE TITLE
Tienes que añadir los scripts de bash que utilices en cada una de las prácticas con extensión .sh

### ISSUE THREAD

**Issue by josejuansanchez** [ivanmp-lm/IAW#2]
Buenas Iván,

Tienes que añadir los scripts de bash que utilizas en cada una de las prácticas con extensión .sh.
Ahora mismo tienes el contenido dentro de un documento con formato Markdown, por lo tanto si yo quisiera ejecutar ese script tendría que copiarlo en un nuevo archivo y ejecutarlo.

Puedes tener las dos cosas, un archivo en formato Markdown y otro con extensión .sh.

¡Buen trabajo!

**Comment by ivanmp-lm** [comment]
Muchas gracias por el aviso, solucionado.
